export const STORE_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Camisola Lakers – LeBron #23',
    team: 'Los Angeles Lakers',
    category: 'Camisola',
    price: 89.99,
    image: './imagens/camisola-lakers-lebron.jpg',
    description: 'Camisola oficial NBA com tecido dry-fit, corte leve e acabamento resistente. Ideal para fãs do LeBron.',
    details: [
      { label: 'Material', value: '100% poliéster respirável' },
      { label: 'Tamanho', value: 'Unisexo' },
      { label: 'SKU', value: 'LB23' },
      { label: 'Disponibilidade', value: 'Em stock' },
    ],
  },
  {
    id: 'prod-2',
    name: 'Camisola Warriors – Curry #30',
    team: 'Golden State Warriors',
    category: 'Camisola',
    price: 89.99,
    image: './imagens/camisola-warriors-curry.jpg',
    description: 'Camisola oficial dos Warriors com padrão moderno e toque suave para usar em jogos e treinos.',
    details: [
      { label: 'Material', value: '100% poliéster respirável' },
      { label: 'Tamanho', value: 'Unisexo' },
      { label: 'SKU', value: 'CR30' },
      { label: 'Disponibilidade', value: 'Em stock' },
    ],
  },
  {
    id: 'prod-3',
    name: 'Camisola Bulls – Jordan #23',
    team: 'Chicago Bulls',
    category: 'Camisola',
    price: 94.99,
    image: './imagens/camisola-bulls-jordan.webp',
    description: 'Edição especial de uma das camisolas mais icónicas do basquetebol, com estilo clássico e toque premium.',
    details: [
      { label: 'Material', value: '100% poliéster respirável' },
      { label: 'Tamanho', value: 'Unisexo' },
      { label: 'SKU', value: 'MJ23' },
      { label: 'Disponibilidade', value: 'Em stock' },
    ],
  },
  {
    id: 'prod-4',
    name: 'Camisola Celtics – Tatum #0',
    team: 'Boston Celtics',
    category: 'Camisola',
    price: 84.99,
    image: './imagens/camisola-celtics-tatum.jpg',
    description: 'Camisola oficial dos Celtics com tecnologia de secagem rápida e visual inspirado no basquetebol moderno.',
    details: [
      { label: 'Material', value: '100% poliéster respirável' },
      { label: 'Tamanho', value: 'Unisexo' },
      { label: 'SKU', value: 'TT00' },
      { label: 'Disponibilidade', value: 'Em stock' },
    ],
  },
  {
    id: 'prod-5',
    name: 'Bola NBA Official Game Ball',
    team: 'NBA',
    category: 'Bola',
    price: 149.99,
    image: './imagens/bola-nba-official.jpg',
    description: 'Bola oficial de jogo, com grip superior e construção durável para treinos intensos e partidas oficiais.',
    details: [
      { label: 'Material', value: 'Couro sintético premium' },
      { label: 'Tamanho', value: '7 (oficial)' },
      { label: 'SKU', value: 'BB-RT' },
      { label: 'Disponibilidade', value: 'Em stock' },
    ],
  },
  {
    id: 'prod-6',
    name: 'Bola de Treino NBA',
    team: 'NBA',
    category: 'Bola',
    price: 49.99,
    image: './imagens/bola-treino-nba.webp',
    description: 'Bola de treino leve e resistente, perfeita para exercícios de isolação, arremessos e dribles.',
    details: [
      { label: 'Material', value: 'Borracha sintética' },
      { label: 'Tamanho', value: '7' },
      { label: 'SKU', value: 'BB-TR' },
      { label: 'Disponibilidade', value: 'Em stock' },
    ],
  },
  {
    id: 'prod-7',
    name: 'Boné NBA – Lakers Edition',
    team: 'Los Angeles Lakers',
    category: 'Acessório',
    price: 34.99,
    image: './imagens/bone-lakers.webp',
    description: 'Boné estilo snapback com logo dos Lakers, perfeito para completar o look do fã de basquetebol.',
    details: [
      { label: 'Material', value: '100% algodão' },
      { label: 'Tamanho', value: 'Ajustável' },
      { label: 'SKU', value: 'LK-ACC' },
      { label: 'Disponibilidade', value: 'Em stock' },
    ],
  },
  {
    id: 'prod-8',
    name: 'Mochila NBA – Warriors',
    team: 'Golden State Warriors',
    category: 'Acessório',
    price: 59.99,
    image: './imagens/mochila-warriors.webp',
    description: 'Mochila com compartimentos para equipamento e estilo inspirado nos Warriors, ideal para o dia a dia.',
    details: [
      { label: 'Material', value: 'Poliéster resistente' },
      { label: 'Tamanho', value: '30L' },
      { label: 'SKU', value: 'GW-BAG' },
      { label: 'Disponibilidade', value: 'Em stock' },
    ],
  },
]

export const PRODUCT_CATEGORIES = ['Todos', ...new Set(STORE_PRODUCTS.map((product) => product.category))]
